# Generated by Django 3.0.8 on 2020-08-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200802_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='sno',
        ),
    ]
